# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
            - name: gitStream repo agent
  # You may pin to the exact commit or the version.
  # uses: linear-b/gitstream-github-action@42fb50e7d6a4f74d85285ebf586091af141b520a
  uses: linear-b/gitstream-github-action@v2
  with:
    # Path of full Repository
    full_repository: 
    # Head Branch Ref to checkout to
    head_ref: 
    # Base Branch Ref to checkout to
    base_ref: 
    # The client payload
    client_payload: 
    # The github app installation id
    installation_id: # optional
    # Resolver url to send results to
    resolver_url: 
    # Optional token for resolver
    resolver_token: # optional
    # Run parser in debug mode
    debug_mode: # optional, default is false
          
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
